/* js/auth.js */
(function (window) {
  window.Auth = window.Auth || {};
  var ROLE_CLAIM = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role";
  var TOKEN_KEY = "jwt_token";
  window.Auth.setToken = function (token) { try { localStorage.setItem(TOKEN_KEY, token); } catch (e) {} if (window.Api && window.Api.setToken) window.Api.setToken(token); };
  window.Auth.getToken = function () { try { return localStorage.getItem(TOKEN_KEY); } catch (e) { return null; } };
  window.Auth.clearToken = function () { try { localStorage.removeItem(TOKEN_KEY); } catch (e) {} if (window.Api && window.Api.clearToken) window.Api.clearToken(); };
  window.Auth.decodeJwt = function (token) { if (!token) return null; try { var parts = token.split("."); if (parts.length < 2) return null; var payload = parts[1].replace(/-/g, "+").replace(/_/g, "/"); var json = decodeURIComponent(escape(window.atob(payload))); return JSON.parse(json); } catch (e) { console.error("Failed to decode JWT", e); return null; } };
  window.Auth.isAdmin = function () { var token = window.Auth.getToken(); var payload = window.Auth.decodeJwt(token); if (!payload) return false; var role = payload[ROLE_CLAIM] || payload.role || payload.roles; if (Array.isArray(role)) return role.indexOf("Admin") !== -1; return role === "Admin"; };
  window.Auth.login = function (email, password) { var body = { email: email, password: password }; return window.Api.fetch("/Auth/login", { method: "POST", body: body }).then(function (res) { var token = (res && (res.token || res.accessToken || (res.data && res.data.token))) || null; if (!token) { if (typeof res === "string" && res.length > 10) token = res; } if (!token) { return Promise.reject(new Error("Login response did not provide a token")); } window.Auth.setToken(token); return { token: token, raw: res }; }); };
  window.Auth.register = function (fullName, email, password) { var body = { fullName: fullName, email: email, password: password }; return window.Api.fetch("/Auth/register", { method: "POST", body: body }); };
  window.Auth.initLoginPage = function () { document.addEventListener("DOMContentLoaded", function () { var form = document.getElementById("login-form"); if (!form) return; var errorEl = document.getElementById("auth-error"); form.addEventListener("submit", function (e) { e.preventDefault(); var email = form.querySelector('input[name="email"]').value; var password = form.querySelector('input[name="password"]').value; window.Auth.login(email, password).then(function () { window.location.href = "/index.html"; }).catch(function (err) { if (errorEl) { errorEl.innerText = err.message || "Login failed"; errorEl.style.display = "block"; } else alert(err.message || "Login failed"); }); }); }); };
  window.Auth.initRegisterPage = function () { document.addEventListener("DOMContentLoaded", function () { var form = document.getElementById("register-form"); if (!form) return; var errorEl = document.getElementById("auth-error"); form.addEventListener("submit", function (e) { e.preventDefault(); var fullName = form.querySelector('input[name="fullName"]').value; var email = form.querySelector('input[name="email"]').value; var password = form.querySelector('input[name="password"]').value; window.Auth.register(fullName, email, password).then(function () { window.location.href = "/login.html"; }).catch(function (err) { if (errorEl) { errorEl.innerText = err.message || "Register failed"; errorEl.style.display = "block"; } else alert(err.message || "Register failed"); }); }); }); };
})(window);
