/* js/cars.js */
(function (window) {
  window.Cars = window.Cars || {};
  window.Cars.getAllCars = function () { return window.Api.fetch("/Car/all", { method: "GET" }); };
  window.Cars.filterCars = function (filterDto) { return window.Api.fetch("/Car/filter", { method: "POST", body: filterDto }); };
  window.Cars.getCarById = function (id) { return window.Api.fetch("/Car/" + encodeURIComponent(id)); };
  function safeText(s) { if (s == null) return ""; return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }
  window.Cars.renderCars = function (items, containerId) { containerId = containerId || "cars-list"; var list = document.getElementById(containerId); if (!list) return; list.innerHTML = ""; if (!items || !items.length) { list.innerHTML = '<p class="text-slate-600 dark:text-slate-400">No cars found.</p>'; return; } for (var i = 0; i < items.length; i++) { var car = items[i]; var card = document.createElement("div"); card.className = "glass card p-4 rounded-xl flex flex-col h-full animate-fade-in"; var img = document.createElement("img"); img.src = car.imageUrl || "/assets/car1.svg"; img.alt = (car.make || "") + " " + (car.model || ""); img.className = "w-full h-48 object-cover rounded-lg mb-3"; var body = document.createElement("div"); body.className = "flex-1"; var title = document.createElement("h3"); title.className = "text-lg font-bold mb-1"; title.innerText = safeText((car.make || "") + " " + (car.model || "")); var meta = document.createElement("p"); meta.className = "text-sm text-slate-600 dark:text-slate-400 mb-3"; meta.innerText = (car.year || "") + " • " + (car.status || ""); var price = document.createElement("div"); price.className = "text-2xl font-bold text-teal-600 dark:text-teal-400 mb-4"; var pVal = car.pricePerDay != null ? Number(car.pricePerDay).toFixed(2) : "0.00"; price.innerText = "$" + pVal + "/day"; var btn = document.createElement("button"); btn.className = "btn btn-primary w-full"; btn.innerText = "Reserve Now"; (function (carId) { btn.addEventListener("click", function () { window.location.href = "/reservations.html?carId=" + encodeURIComponent(carId); }); })(car.id); body.appendChild(title); body.appendChild(meta); body.appendChild(price); card.appendChild(img); card.appendChild(body); card.appendChild(btn); list.appendChild(card); } };
  window.Cars.initCarsPage = function () { document.addEventListener("DOMContentLoaded", function () { var list = document.getElementById("cars-list"); if (!list) return; list.innerHTML = "<p>Loading...</p>"; window.Cars.getAllCars().then(function (items) { window.Cars.renderCars(items || []); }).catch(function () { list.innerHTML = '<p class="text-red-500">Failed to load cars.</p>'; }); var form = document.getElementById("filter-form"); if (!form) return; form.addEventListener("submit", function (e) { e.preventDefault(); var make = form.querySelector('input[name="make"]').value; var model = form.querySelector('input[name="model"]').value; var year = form.querySelector('input[name="year"]').value; var minPrice = form.querySelector('input[name="minPrice"]').value; var maxPrice = form.querySelector('input[name="maxPrice"]').value; var status = form.querySelector('select[name="status"]').value; var dto = { make: make || null, model: model || null, year: year ? parseInt(year, 10) : null, minPrice: minPrice ? parseFloat(minPrice) : null, maxPrice: maxPrice ? parseFloat(maxPrice) : null, status: status || null }; window.Cars.filterCars(dto).then(function (res) { window.Cars.renderCars(res || []); }).catch(function () { alert("Filter failed"); }); }); }); };
})(window);
