/* js/reservations.js */
(function (window) {
  window.Reservations = window.Reservations || {};
  window.Reservations.createReservation = function (dto) { return window.Api.fetch("/Reservation/create", { method: "POST", body: dto }); };
  window.Reservations.getMyReservations = function () { return window.Api.fetch("/Reservation/my", { method: "GET" }); };
  window.Reservations.updateReservation = function (dto) { return window.Api.fetch("/Reservation/update", { method: "PUT", body: dto }); };
  window.Reservations.deleteReservation = function (id) { return window.Api.fetch("/Reservation/" + encodeURIComponent(id), { method: "DELETE" }); };
  window.Reservations.initReservationsPage = function () { document.addEventListener("DOMContentLoaded", function () { var list = document.getElementById("reservations-list"); if (!list) return; list.innerHTML = "<p>Loading...</p>"; function load() { window.Reservations.getMyReservations().then(function (items) { renderList(items || []); }).catch(function () { list.innerHTML = '<p class="text-red-500">Failed to load reservations.</p>'; }); }
    function renderList(items) { list.innerHTML = ""; if (!items || !items.length) { list.innerHTML = '<p class="text-slate-600 dark:text-slate-400">No reservations.</p>'; return; } for (var i = 0; i < items.length; i++) { var r = items[i]; var card = document.createElement("div"); card.className = "glass card p-4 rounded-xl mb-4 animate-fade-in"; var header = document.createElement("div"); header.className = "flex justify-between items-start mb-3"; var left = document.createElement("div"); var title = document.createElement("div"); title.className = "font-bold text-lg"; title.innerText = (r.car && (r.car.make + " " + r.car.model)) || ("Reservation #" + (r.id || "")); var meta = document.createElement("div"); meta.className = "text-sm text-slate-600 dark:text-slate-400 mt-1"; meta.innerText = (r.startDate ? new Date(r.startDate).toLocaleString() : "") + " → " + (r.endDate ? new Date(r.endDate).toLocaleString() : ""); left.appendChild(title); left.appendChild(meta); var statusBadge = document.createElement("span"); statusBadge.className = "badge badge-teal"; statusBadge.innerText = r.status || "N/A"; header.appendChild(left); header.appendChild(statusBadge); var actions = document.createElement("div"); actions.className = "flex gap-2"; var cancelBtn = document.createElement("button"); cancelBtn.className = "btn btn-ghost small"; cancelBtn.innerText = "Cancel"; (function (rid) { cancelBtn.addEventListener("click", function () { if (!confirm("Cancel reservation?")) return; window.Reservations.deleteReservation(rid).then(function () { load(); }).catch(function () { alert("Failed to cancel"); }); }); })(r.id); var payBtn = document.createElement("button"); payBtn.className = "btn btn-primary small"; payBtn.innerText = "Pay"; (function (rid) { payBtn.addEventListener("click", function () { if (!window.Payments || !window.Payments.createPaymentSession) { alert('Payments module not available'); return; } try { window.Payments.createPaymentSession(rid).catch(function (err) { alert(err.message || 'Payment failed'); }); } catch (e) { alert('Payment failed'); } }); })(r.id); actions.appendChild(payBtn); actions.appendChild(cancelBtn); card.appendChild(header); card.appendChild(actions); list.appendChild(card); } }
    var form = document.getElementById("reservation-create-form"); if (form) { var params = (function () { var q = {}; var ps = window.location.search.substring(1).split("&"); for (var i = 0; i < ps.length; i++) { var p = ps[i].split("="); if (p[0]) q[decodeURIComponent(p[0])] = decodeURIComponent(p[1] || ""); } return q; })(); if (params.carId) { var el = form.querySelector('input[name="carId"]'); if (el) el.value = params.carId; } form.addEventListener("submit", function (e) { e.preventDefault(); var carId = form.querySelector('input[name="carId"]').value; var startDate = form.querySelector('input[name="startDate"]').value; var endDate = form.querySelector('input[name="endDate"]').value; var dto = { carId: parseInt(carId, 10), startDate: startDate, endDate: endDate }; window.Reservations.createReservation(dto).then(function (res) { window.location.href = "/reservations.html"; }).catch(function () { alert("Failed to create reservation"); }); }); }
    load(); }); };
})(window);
